### ISSUE TITLE
As an efficient salesman, I can set meeting / call time with contacts 

### ISSUE THREAD

**Issue by sebastiantoh** [AY2021S1-CS2103T-T11-1/tp#12]
... so that can plan my meetings without another app

- [x] Add model and storage (to be done in #61)
- [x] Command parsing (Create, Read, Delete)
- [ ] Tests (to be done in #60)
- [x] GUI (to be done in #10)
